version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ToDoAppDbPass1
    ports:
      - "1433:1433"
    networks:
      - todo-app-network
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "5000:5000"
    networks:
      - todo-app-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ToDoAppDb;User=sa;Password=ToDoAppDbPass1;
    depends_on:
      - sqlserver

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    networks:
      - todo-app-network
    depends_on:
      - backend

networks:
  todo-app-network:
    driver: bridge

volumes:
  sqlvolume:
    driver: local
