version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ToDoAppDbPass1
    ports:
      - "1433:1433"
    networks:
      - todonet
    volumes:
      - sqlserverdata:/var/opt/mssql

networks:
  todonet:
    driver: bridge

volumes:
  sqlserverdata:
    driver: local
